### ISSUE TITLE
Project Progress Report

### ISSUE THREAD

**Issue by jaredfreedman** [jaredfreedman/edna_metabarcoding#2] opened 2021-11-04 16:54 UTC

**Comment by ssidder** [comment] 2021-11-04 17:56
I have found working through example data and R vignettes to be really helpful and a step in my workflow as well. In particular, it's been helpful to ensure that functions are working properly and to cross reference data types when I get errors... I can go back to code that I've already run and investigate quickly rather than spend additional time trying to figure out what should be happening.

**Comment by maddie-hicks** [comment] 2021-11-04 17:56
I think eDNA is a super cool tool, so your project sounds super interesting!  I'm also running into the issue of dealing with files that are too large to put onto GitHub (I'm working with GIS shapefiles and raster files), so I feel your struggle.

**Comment by varyl97** [comment] 2021-11-04 17:56
Great job Jared! It sounds like you've been able to adequately address your setbacks and for the current setbacks, e.g., the R package overwriting folders, it sounds like you're thinking about solutions in a very clear and logical way. Glad to see that you're getting some eDNA results aligned with literature expectations!

**Comment by sielerjm** [comment] 2021-11-04 17:57
Nice work Jared. With the naming convention issue, you might be able to make a script that auto-renames files with a format that you prefer for your pipeline. That way you don't have to manually alter their names. This might depend on if the software that creates the file and filenames after you alter the settings has a consistent formatting scheme.

**Comment by Medelinkant** [comment] 2021-11-04 17:57
Nice progress! I thought it was valuable to discuss your specific folder creation issue with the class. Someone might have experienced or currently tackling a similar problem.  Hope you find the best resolution.

**Comment by JustinHockett** [comment] 2021-11-04 17:58
Congrats on getting your sequences back (or almost back)! I think you should look into a GIS course to see if you can use it for spatial analyses when you look at patterns across the GC and its tribs. Best of luck on the next step of implementing your data in the pipeline that you've worked out!

**Comment by kjtonra** [comment] 2021-11-04 17:58
Congrats on getting sequence results back! Integrating all of the other stuff sounds like it'll be kind of a chore, but it looks like you're on track and have a good setup for keeping everything organized. I'm not sure if this is a recommended practice, but I sometimes make a folder to keep files like the ones you're talking about and I'll just separate them by date or iteration or something like that. I feel better about archiving some of the created files for a week or so in case I need them again, but delete once the project is completed.

**Comment by dymite** [comment] 2021-11-04 17:59
Great work! I don't think you will have any problems finding COI invert sequences to align - you should definitely do that in geneious, too!! I think its great that you are committed to keeping your fasta files and other version control things in order - you will absolutely be thanking yourself for that later!

**Comment by BenjaminDalziel** [comment] 2021-11-04 18:05
1. Sounds like great progress and congrats on getting an eDNA pipeline up and running in your lab!
2. For saving outputs - I wonder if you should consider Susie's suggestion of saving the configurations that produced each output, so you can go back an reproduce them more easily.

**Comment by cheyennejarman** [comment] 2021-11-04 18:05
I think it is very strategic that you are taking the time to walk through the tutorial. I find when new packages or SW have those - it is worth taking the time to walk through the examples and know that the package works on your machine. It makes for troubleshooting a little easier if you are getting an error with your data.

**Closed** 2021-11-30 18:06 UTC
